# This workflow will build ccu-jack

name: CI

# create special debian-vn.n.n tags for releasing that contain changelogs updates
on:
  push:
    tags:
      - "debian-v*.*.*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: true
        # this is needed to fetch tags
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.x'

    - name: Set up Build environment
      run: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -yV build-essential devscripts equivs debmake git-buildpackage

    - name: Build debian package
      # ignore branch as we are on-push-tags, no branch information is available
      run: |
        gbp buildpackage --git-ignore-branch --git-upstream-tag='v%(version)s' -b

    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          /home/runner/work/ccu-jack/ccu-jack_*
        name: ccu-jack-${{ github.sha }}
        retention-days: 30

    - name: Create release with debian package
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /home/runner/work/ccu-jack/ccu-jack_*.deb
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
